### ISSUE TITLE
Load file to variable

### ISSUE THREAD

**Issue by PejmanNik** [jondot/hygen#69] opened 2018-09-05 08:27 UTC
Hi, Thank you for your greate project.

how can we read a file and based on that make our template?
for example, read the file and run a foreach on it and make template sections?

**Comment by jondot** [comment] 2018-09-05 08:49
You have two ways:

1. Template code is completely javascript code - so you can try it.
2. You can use helper `.hygen.js` http://www.hygen.io/faq#generating-from-a-deep-directory-and-inject-to-an-upper-one

**Comment by PejmanNik** [comment] 2018-09-05 12:07
Thank you so much.

i use:
`<% import data from './templates'; %>`

but i got:
`SyntaxError: Unexpected identifier while compiling ejs`

it is so hard to debug because I can't see the error.

**Comment by PejmanNik** [comment] 2018-09-05 12:38
Thank you again. 

sorry 😔 but now i got:

ReferenceError: ejs:3
    1| export default {
    2|
 >> 3| <% const data = require('./templates') %>

require is not defined

**Comment by jondot** [comment] 2018-09-05 16:51
Interesting. Can you publish a git repo with these templates - I can try to fix them for you.

**Comment by eightyfive** [comment] 2018-09-19 07:04
I have the same problem.

```
---
to: src/zip.js
---
<% const _ = require("lodash"); %>

export const zipped = <%= JSON.stringify(_.zipObject(keys, vals)) %>;
```

Same error:
> require is not defined

**Comment by jondot** [comment] 2018-10-05 09:30
@eightyfive try looking at the `.hygen.js` file to extend your templates:
http://www.hygen.io/faq#generating-from-a-deep-directory-and-inject-to-an-upper-one

**Comment by jondot** [comment] 2018-10-05 09:30
closing this but feel free to reopen if issue persists or `.hygen.js` doesn't cover it. I would be very excited to find a new way to help.

**Closed by jondot** 2018-10-05 09:30 UTC

**Comment by eightyfive** [comment] 2018-10-05 15:56
Hi, thanks, I’ll try that, that may be enough, although I’m thinking you cannot embed “require’d” logic in a template, I did not have the use case yet really, but is that not limitating? Or is it by design: template should remain simple, self-contained.

ZipObject is a good illustration of that limitation, do we want to reimplement over and over that simple util?

Basically I’m thinking about it would be nice to have some kind of “controller” layer passing _processed_ data to the .ejs.t “view”.

**Comment by ziaadini** [comment] 2020-03-09 06:46
i have a problem how can i use .hygen.js variables in prompter? i need some data for check some validations.

**Comment by jamaica474** [comment] 2020-04-28 09:18
I have 2 files, A and B, both generated by Hygen in a single run. Challenge I'm trying to solve is having contents of B to A().

So, generate A, then require it in B, and run it. As of now I wan't able to find a way to do so.
