### ISSUE TITLE
Bug: Chalk terminal colours don't show work for `help` action

### ISSUE THREAD

**Issue by Darth-Knoppix** [jondot/hygen#265] opened 2020-10-02 01:19 UTC
## Context

- Using version **6.04** of Hygen from npx
- The generator name is `landing-page`

## Problem
Running the following command `npx hygen landing-page help`, doesn't work as expected.

The **landing-page/help/index.ejs.t** contents:

```yaml
---
message: |
    - hygen {bold mailer} new --name [NAME]
---
```

The `npx hygen landing-page help` output:

```sh
Loaded templates: _templates
[object Function] help:
- hygen {bold mailer} new --name [NAME]
```

## Note

Version **4.x** of Hygen works as expected and does bold/color in the terminal correctly.

Is this a bug or has the way that `help` is supposed to work, changed since version 4?

**Comment by libinvarghese** [comment] 2021-01-20 23:40
This can be fixed by #248

**Comment by linkors** [comment] 2021-05-20 02:32
I still have the same problem using version 6.1.0 (event the fixed has been merged). Or do we still need to do the workaround?

**Comment by valinaga** [comment] 2021-07-02 15:14
The PR above didn't fix the issue. the version 6.1.0 still have this bug. any idea on how to dix it?
Thanks

**Comment by jerryjvl** [comment] 2021-07-11 05:23
Fix for this issue is in https://github.com/jondot/hygen/pull/335

**Closed** 2022-02-21 07:34 UTC

**Comment by foxted** [comment] 2022-11-22 11:12
The issue is still present in 6.2.11. On a fresh install, running hygen init self then hygen generator help the chalk templates aren't rendered.

**Comment by karlmarxlopez** [comment] 2023-03-01 06:30
Here's a patch to fix this issue.


```diff
diff --git a/node_modules/hygen/dist/logger.js b/node_modules/hygen/dist/logger.js
index 312f112..5194ca3 100644
--- a/node_modules/hygen/dist/logger.js
+++ b/node_modules/hygen/dist/logger.js
@@ -4,8 +4,9 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
 };
 Object.defineProperty(exports, "__esModule", { value: true });
 const chalk_1 = __importDefault(require("chalk"));
+const template = require("chalk/source/templates");
 // chalk 4.1.2 doesn't type template property
-const { yellow, red, green, magenta, template } = chalk_1.default;
+const { yellow, red, green, magenta } = chalk_1.default;
 class Logger {
     constructor(log) {
         this.log = log;
```

**Comment by antitoxic** [comment] 2024-02-22 16:19
Also confirming this is still an issue and I have to patch `hygen` to make it work (kudos to @SpaghettiC0des for the patch).

**Comment by tobiashochguertel** [comment] 2024-04-10 19:31
```
patches/hygen+6.2.11+001+chalk.patch
```

```
npx patch-package
```

**Comment by Maker-Mark** [comment] 2024-04-18 14:54
@jondot Is there a plan to fix this or remove the reference in the docs?
